### ISSUE TITLE
讲讲你的编程之路

### ISSUE THREAD

**Issue by imsobear** [fengmk2/ama#3]
RT

**Comment by fengmk2** [comment]
- 大学之前只玩电脑游戏
- 大学在宿舍实在无聊，美剧全部看完，就自学编程打发时间
- 从 [单片机](http://www.cnblogs.com/fengmk2/archive/2007/03/11/670955.html)，到去校园网下载北大青鸟的视频学 Asp.net （黑历史），然后学了到现在还是不太会的 CSS，JavaScript 就开始在学校接点小项目挣点夜宵费。
- 08年毕业前遇上就业困难，实习先是去了广州一下在微软外包的公司，做 .Net 开发。
  后来在同班同学的内推下，去了珠海金山软件面试，意外地拿到 offer。
- 毕业后就直奔珠海金山，做了两年的 Python 开发。准确地说用 Python 做各种类型的开发。爬虫，病毒库制作，网站，高性能查毒服务 API，金山清理专家后台等等。
- 直到360将金山清理专家直接拦截卸载后，突然间没活干了。
- 于是考虑回广州工作。毕业两年后，2010年第一次跳槽，加入 UCWeb，做 Python + .Net 的混合开发，还短暂做了一个 PHP 的网盘项目。
- 在金山到 UCWeb 期间，正遇上微博大热，跟 @qleelulu 做的 FaWave 也算是顶峰时期，也是通过 FaWave，学习了许多普通 JS 很难用得到的场景，如如何在 JS 中进行二进制数据的转换和传输。
- 机缘巧合的一通电话，在金山的前老板，给当时还在淘宝的玄澄推荐了我，说我能使用 Python 写一个高性能的 Web 框架，于是就得到了一次面试机会。
- 后来还真的去了杭州面试，尼玛，还真的过了，而且当场发 offer，在去机场回程的路上，感觉好像在做梦。
- 2011年2月14日正式入职淘宝网，从事 Node.js 相关 Web 开发工作。因为前几年的工作经历都是在 Web 相关的，所以很快就上手。
- 当时中国市场可以说是没有几个人能直接招聘进来就懂 Node.js 的，于是我们成立了 CNode 社区，主要就是吸引其他语言的人过来，然后培养，然后变成我们的人。如著名的@朴灵 老师就是从一个能兼容 IE6的男人变成当今的 Node.js 大神。
- Node.js 非 C++部分代码其实很容易看懂，然后就经常参与 github 上面的各种热门模块，然后自己也造了非常多的模块，如 https://github.com/node-modules 下的许多模块，都是我跟 @dead-horse 不断累积下来的。
- 我自己一直维护并且写了很多年才算稳定的模块应该就是 [urllib](https://github.com/node-modules/urllib)，不要问我为什么叫这个名字，因为我是 『@Python发烧友』。
- 如果要讲讲我怎么将 Node.js 代码写得高质量的方法，那其实我的方法就只有一个，就是尽可能地写好单元测试。没有单元测试的模块，其实我是拒绝的。

未来我估计还是会继续玩  Node.js 的，因为它不仅仅是 Web 服务端领域，而且越来越多的领域已经被它入侵，如桌面软件，如移动端软件，只是目前做的人还是比较少。

不要想让 Node.js 将一个大型软件都做完了，它只是其中一个节点而已。

正如我们每个人，也只是这个世界上的一个小小节点。

**Comment by fengmk2** [comment]
呃，荔枝 web 竟然还能找到 https://code.google.com/p/litchiweb/

**Comment by lichunqiang** [comment]
:+1: 楷模

**Comment by imsobear** [comment]
好崇拜苏千大神 :smile:
