### ISSUE TITLE
What does your development environment look like?

### ISSUE THREAD

**Issue by arthurvr** [fengmk2/ama#4]
Hardware, editor, terminal, ...

**Comment by fengmk2** [comment]
- Hardware: MBP 2013

![image](https://cloud.githubusercontent.com/assets/156269/11058672/61990044-87cf-11e5-8712-e973941496d0.png)
- Editor: [atom](https://atom.io/), yeah, I love it much!

![image](https://cloud.githubusercontent.com/assets/156269/11058659/473115de-87cf-11e5-87e6-1b0c9cfb91fc.png)
- Terminal: Mac default terminal, use `Pro` theme. 

![image](https://cloud.githubusercontent.com/assets/156269/11058686/7517fe68-87cf-11e5-9c1d-b90b6fc0710d.png)

Using `nvm` for node env switch.
