### ISSUE TITLE
How do you learn a new technology? Do you use materials like books or tutorial videos?

### ISSUE THREAD

**Issue by konekoya** [fengmk2/ama#6]

**Comment by fengmk2** [comment]
I think you can read Chinese, I wrote a little bit of my career on #3.

I don't have must time to reading books and tutorial videos currently.

Instead, I read article, blog, github project and codes.

**Comment by konekoya** [comment]
Yes, actually I'm a native Chinese speaker. But Just think that asking questions in English would be better for people who don't know Chinese. Thank you :)
